/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import conversiones.MetodosDeConversiones;
import javax.swing.JOptionPane;

/**
 *
 * @author Julio Cesar Morales Sierra
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        textarea.setEditable(false);
        TituloBit.setEditable(false);
        TituloByte.setEditable(false);
        TituloKB.setEditable(false);
        TituloMB.setEditable(false);
        TituloGB.setEditable(false);
        TituloTB.setEditable(false);
        TituloPB.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BCalculo = new javax.swing.JButton();
        TituloBit = new javax.swing.JTextField();
        TituloByte = new javax.swing.JTextField();
        TituloKB = new javax.swing.JTextField();
        TituloMB = new javax.swing.JTextField();
        TituloGB = new javax.swing.JTextField();
        TituloTB = new javax.swing.JTextField();
        TituloPB = new javax.swing.JTextField();
        NumeroBit = new javax.swing.JTextField();
        NumeroByte = new javax.swing.JTextField();
        NumeroPB = new javax.swing.JTextField();
        NumeroMB = new javax.swing.JTextField();
        NumeroKB = new javax.swing.JTextField();
        NumeroGB = new javax.swing.JTextField();
        NumeroTB = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Bborrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textarea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(720, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BCalculo.setText("Calcular");
        BCalculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCalculoActionPerformed(evt);
            }
        });
        getContentPane().add(BCalculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 120, -1));

        TituloBit.setText("Bit");
        TituloBit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TituloBitActionPerformed(evt);
            }
        });
        getContentPane().add(TituloBit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 70, -1));

        TituloByte.setText("Byte");
        TituloByte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TituloByteActionPerformed(evt);
            }
        });
        getContentPane().add(TituloByte, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 70, -1));

        TituloKB.setText("KiloByte");
        TituloKB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TituloKBActionPerformed(evt);
            }
        });
        getContentPane().add(TituloKB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 70, -1));

        TituloMB.setText("MegaByte");
        TituloMB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TituloMBActionPerformed(evt);
            }
        });
        getContentPane().add(TituloMB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        TituloGB.setText("GigaByte");
        TituloGB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TituloGBActionPerformed(evt);
            }
        });
        getContentPane().add(TituloGB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 70, -1));

        TituloTB.setText("TeraByte");
        TituloTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TituloTBActionPerformed(evt);
            }
        });
        getContentPane().add(TituloTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 70, -1));

        TituloPB.setText("PetaByte");
        TituloPB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TituloPBActionPerformed(evt);
            }
        });
        getContentPane().add(TituloPB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 70, -1));

        NumeroBit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroBitActionPerformed(evt);
            }
        });
        getContentPane().add(NumeroBit, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 180, -1));

        NumeroByte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroByteActionPerformed(evt);
            }
        });
        getContentPane().add(NumeroByte, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 180, -1));
        getContentPane().add(NumeroPB, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 180, -1));
        getContentPane().add(NumeroMB, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 180, -1));
        getContentPane().add(NumeroKB, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 180, -1));

        NumeroGB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroGBActionPerformed(evt);
            }
        });
        getContentPane().add(NumeroGB, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 180, -1));
        getContentPane().add(NumeroTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 180, -1));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Sistema de numeración");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, -1, 20));

        Bborrar.setText("Borrar");
        Bborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BborrarActionPerformed(evt);
            }
        });
        getContentPane().add(Bborrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 120, -1));

        textarea.setColumns(16);
        textarea.setRows(5);
        jScrollPane1.setViewportView(textarea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 190, 290));

        jLabel4.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Medidas de almacenamiento");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 20));

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Calculadora de Unidades de Almacenamiento");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 400, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TituloByteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TituloByteActionPerformed
        // TODO add your handling code here:
        TituloByte.setEnabled(false);
    }//GEN-LAST:event_TituloByteActionPerformed

    private void TituloKBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TituloKBActionPerformed
        // TODO add your handling code here
        TituloKB.setEnabled(false);
    }//GEN-LAST:event_TituloKBActionPerformed

    private void NumeroByteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroByteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumeroByteActionPerformed

    private void BCalculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCalculoActionPerformed
        // TODO add your handling code here:
        MetodosDeConversiones conv = new MetodosDeConversiones();
        try {
            if (!NumeroBit.getText().equals("")) {
                NumeroByte.setText(Double.toString(conv.conversion_Subir_Byte(Integer.parseInt(NumeroBit.getText()))));
                NumeroKB.setText(Double.toString(conv.conversion_subir(conv.ultimo_Numero())));
                NumeroMB.setText(Double.toString(conv.conversion_subir(conv.ultimo_Numero())));
                NumeroGB.setText(Double.toString(conv.conversion_subir(conv.ultimo_Numero())));
                NumeroTB.setText(Double.toString(conv.conversion_subir(conv.ultimo_Numero())));
                NumeroPB.setText(Double.toString(conv.conversion_subir(conv.ultimo_Numero())));
                textarea.setText("Binario: " + conv.convertir_A_Binario(Long.parseLong(NumeroBit.getText())) + "\n"
                        + "Quinario: " + conv.convertir_A_Quinario(Long.parseLong(NumeroBit.getText())) + "\n"
                        + "Octal: " + conv.convertir_A_Octal(Long.parseLong(NumeroBit.getText())) + "\n"
                        + "Hexadecimal: " + conv.convertir_A_Hexadecimal(Long.parseLong(NumeroBit.getText())));
                BCalculo.setEnabled(false);

            } else if (!NumeroByte.getText().equals("")) {
                NumeroBit.setText(Double.toString(conv.conversion_Bajar_Bit(Integer.parseInt(NumeroByte.getText()))));
                NumeroKB.setText(Double.toString(conv.conversion_subir(Integer.parseInt(NumeroByte.getText()))));
                NumeroMB.setText(Double.toString(conv.conversion_subir(conv.ultimo_Numero())));
                NumeroGB.setText(Double.toString(conv.conversion_subir(conv.ultimo_Numero())));
                NumeroTB.setText(Double.toString(conv.conversion_subir(conv.ultimo_Numero())));
                NumeroPB.setText(Double.toString(conv.conversion_subir(conv.ultimo_Numero())));
                textarea.setText("Binario: " + conv.convertir_A_Binario(Long.parseLong(NumeroByte.getText())) + "\n"
                        + "Quinario: " + conv.convertir_A_Quinario(Long.parseLong(NumeroByte.getText())) + "\n"
                        + "Octal: " + conv.convertir_A_Octal(Long.parseLong(NumeroByte.getText())) + "\n"
                        + "Hexadecimal: " + conv.convertir_A_Hexadecimal(Long.parseLong(NumeroByte.getText())));
                BCalculo.setEnabled(false);

            } else if (!NumeroKB.getText().equals("")) {
                NumeroByte.setText(Double.toString(conv.convercion_bajar(Integer.parseInt(NumeroKB.getText()))));
                NumeroBit.setText(Double.toString(conv.conversion_Bajar_Bit(conv.ultimo_Numero())));
                NumeroMB.setText(Double.toString(conv.conversion_subir(Integer.parseInt(NumeroKB.getText()))));
                NumeroGB.setText(Double.toString(conv.conversion_subir(conv.ultimo_Numero())));
                NumeroTB.setText(Double.toString(conv.conversion_subir(conv.ultimo_Numero())));
                NumeroPB.setText(Double.toString(conv.conversion_subir(conv.ultimo_Numero())));
                textarea.setText("Binario: " + conv.convertir_A_Binario(Long.parseLong(NumeroKB.getText())) + "\n"
                        + "Quinario: " + conv.convertir_A_Quinario(Long.parseLong(NumeroKB.getText())) + "\n"
                        + "Octal: " + conv.convertir_A_Octal(Long.parseLong(NumeroKB.getText())) + "\n"
                        + "Hexadecimal: " + conv.convertir_A_Hexadecimal(Long.parseLong(NumeroKB.getText())));
                BCalculo.setEnabled(false);

            } else if (!NumeroMB.getText().equals("")) {
                NumeroKB.setText(Double.toString(conv.convercion_bajar(Integer.parseInt(NumeroMB.getText()))));
                NumeroByte.setText(Double.toString(conv.convercion_bajar(conv.ultimo_Numero())));
                NumeroBit.setText(Double.toString(conv.conversion_Bajar_Bit(conv.ultimo_Numero())));
                NumeroGB.setText(Double.toString(conv.conversion_subir(Integer.parseInt(NumeroMB.getText()))));
                NumeroTB.setText(Double.toString(conv.conversion_subir(conv.ultimo_Numero())));
                NumeroPB.setText(Double.toString(conv.conversion_subir(conv.ultimo_Numero())));
                textarea.setText("Binario: " + conv.convertir_A_Binario(Long.parseLong(NumeroMB.getText())) + "\n"
                        + "Quinario: " + conv.convertir_A_Quinario(Long.parseLong(NumeroMB.getText())) + "\n"
                        + "Octal: " + conv.convertir_A_Octal(Long.parseLong(NumeroMB.getText())) + "\n"
                        + "Hexadecimal: " + conv.convertir_A_Hexadecimal(Long.parseLong(NumeroMB.getText())));
                BCalculo.setEnabled(false);

            } else if (!NumeroGB.getText().equals("")) {

                NumeroMB.setText(Double.toString(conv.convercion_bajar(Integer.parseInt(NumeroGB.getText()))));
                NumeroKB.setText(Double.toString(conv.convercion_bajar(conv.ultimo_Numero())));
                NumeroByte.setText(Double.toString(conv.convercion_bajar(conv.ultimo_Numero())));
                NumeroBit.setText(Double.toString(conv.conversion_Bajar_Bit(conv.ultimo_Numero())));
                NumeroTB.setText(Double.toString(conv.conversion_subir(Integer.parseInt(NumeroGB.getText()))));
                NumeroPB.setText(Double.toString(conv.conversion_subir(conv.ultimo_Numero())));
                textarea.setText("Binario: " + conv.convertir_A_Binario(Long.parseLong(NumeroGB.getText())) + "\n"
                        + "Quinario: " + conv.convertir_A_Quinario(Long.parseLong(NumeroGB.getText())) + "\n"
                        + "Octal: " + conv.convertir_A_Octal(Long.parseLong(NumeroGB.getText())) + "\n"
                        + "Hexadecimal: " + conv.convertir_A_Hexadecimal(Long.parseLong(NumeroGB.getText())));
                BCalculo.setEnabled(false);
            } else if (!NumeroTB.getText().equals("")) {
                NumeroGB.setText(Double.toString(conv.convercion_bajar(Integer.parseInt(NumeroTB.getText()))));
                NumeroMB.setText(Double.toString(conv.convercion_bajar(conv.ultimo_Numero())));
                NumeroKB.setText(Double.toString(conv.convercion_bajar(conv.ultimo_Numero())));
                NumeroByte.setText(Double.toString(conv.convercion_bajar(conv.ultimo_Numero())));
                NumeroBit.setText(Double.toString(conv.conversion_Bajar_Bit(conv.ultimo_Numero())));
                NumeroPB.setText(Double.toString(conv.conversion_subir(Integer.parseInt(NumeroTB.getText()))));
                textarea.setText("Binario: " + conv.convertir_A_Binario(Long.parseLong(NumeroTB.getText())) + "\n"
                        + "Quinario: " + conv.convertir_A_Quinario(Long.parseLong(NumeroTB.getText())) + "\n"
                        + "Octal: " + conv.convertir_A_Octal(Long.parseLong(NumeroTB.getText())) + "\n"
                        + "Hexadecimal: " + conv.convertir_A_Hexadecimal(Long.parseLong(NumeroTB.getText())));
                BCalculo.setEnabled(false);

            } else if (!NumeroPB.getText().equals("")) {
                NumeroTB.setText(Double.toString(conv.convercion_bajar(Integer.parseInt(NumeroPB.getText()))));
                NumeroGB.setText(Double.toString(conv.convercion_bajar(conv.ultimo_Numero())));
                NumeroMB.setText(Double.toString(conv.convercion_bajar(conv.ultimo_Numero())));
                NumeroKB.setText(Double.toString(conv.convercion_bajar(conv.ultimo_Numero())));
                NumeroByte.setText(Double.toString(conv.convercion_bajar(conv.ultimo_Numero())));
                NumeroBit.setText(Double.toString(conv.conversion_Bajar_Bit(conv.ultimo_Numero())));
                textarea.setText("Binario: " + conv.convertir_A_Binario(Long.parseLong(NumeroPB.getText())) + "\n"
                        + "Quinario: " + conv.convertir_A_Quinario(Long.parseLong(NumeroPB.getText())) + "\n"
                        + "Octal: " + conv.convertir_A_Octal(Long.parseLong(NumeroPB.getText())) + "\n"
                        + "Hexadecimal: " + conv.convertir_A_Hexadecimal(Long.parseLong(NumeroPB.getText())));
                BCalculo.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(null, "Debes ingresar un número...");
                BCalculo.setEnabled(true);
            }

        } catch (Exception e) {
              JOptionPane.showMessageDialog(null, "Debes ingresar un número...");
        }


    }//GEN-LAST:event_BCalculoActionPerformed

    private void TituloBitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TituloBitActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_TituloBitActionPerformed

    private void TituloMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TituloMBActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_TituloMBActionPerformed

    private void TituloGBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TituloGBActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_TituloGBActionPerformed

    private void TituloTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TituloTBActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_TituloTBActionPerformed

    private void TituloPBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TituloPBActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_TituloPBActionPerformed

    private void NumeroGBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroGBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumeroGBActionPerformed

    private void NumeroBitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroBitActionPerformed
        // TODO add your handling code here:       

    }//GEN-LAST:event_NumeroBitActionPerformed

    private void BborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BborrarActionPerformed
        // TODO add your handling code here:
        NumeroBit.setText("");
        NumeroByte.setText("");
        NumeroKB.setText("");
        NumeroMB.setText("");
        NumeroGB.setText("");
        NumeroTB.setText("");
        NumeroPB.setText("");
        textarea.setText("");
        BCalculo.setEnabled(true);
    }//GEN-LAST:event_BborrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCalculo;
    private javax.swing.JButton Bborrar;
    private javax.swing.JTextField NumeroBit;
    private javax.swing.JTextField NumeroByte;
    private javax.swing.JTextField NumeroGB;
    private javax.swing.JTextField NumeroKB;
    private javax.swing.JTextField NumeroMB;
    private javax.swing.JTextField NumeroPB;
    private javax.swing.JTextField NumeroTB;
    private javax.swing.JTextField TituloBit;
    private javax.swing.JTextField TituloByte;
    private javax.swing.JTextField TituloGB;
    private javax.swing.JTextField TituloKB;
    private javax.swing.JTextField TituloMB;
    private javax.swing.JTextField TituloPB;
    private javax.swing.JTextField TituloTB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textarea;
    // End of variables declaration//GEN-END:variables
}
